[project]
name = "paradox-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.16.4",
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "openrouter>=1.2.15",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.41",
    "sqlmodel[asyncio]>=0.0.24",
    "uvicorn>=0.51.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.4",
]

[tool.pytest.ini_options]
pythonpath = ["."]
