"""empty message

Revision ID: 7b35cf258c85
Revises: 8d9002773cb1
Create Date: 2026-01-23 20:55:05.201760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b35cf258c85'
down_revision: Union[str, Sequence[str], None] = '8d9002773cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute('UPDATE item SET tagline = name WHERE tagline IS NULL')
    op.alter_column('item', sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'tagline')
    # ### end Alembic commands ###
